services:
  spring-dbunit-postgres-service:
    image: postgres:17.4
    container_name:  spring-dbunit-postgres-container
    ports:
      - 15432:5432
    volumes:
      - ./database/postgresql/init:/docker-entrypoint-initdb.d
      - spring-dbunit-postgres-data-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Tokyo
    command: postgres -c 'max_connections=1000'
    restart: always
    user: root
volumes:
  spring-dbunit-postgres-data-storage:
